.TH capitan "6" "March 2016" "CAPITAN SEVILLA 1.0.3" "Save Seville from the evil Torrebruno"

.SH NAME
capitan \- is a open-source update to the classic platform game from Spain, that captivates adults and children since the late 1980s.
.br

.SH SYNOPSIS
.B capitan
.RI [ introduction ]
.RI [ parts ]
.RI [ menu ]
.RI [ first ]
.RI [ second ]
.RI [ screen ]
.RI [ controls ]
.RI [ actions ]
.RI [ advice ]
.RI [ differences ]
.RI [ license ]
.br

.SH INTRODUCTION
A calm day begins in Seville. Mariano Lopez goes to his job as sausage delivery man. Meanwhile, at Santiponce's interestratospheric devices centre, everybody is getting ready to the first fully spanish rocket launch, designed by famous Dr. Torrebruno, an eminent nuclear physicist who had to leave the project prematurely, due to a strange mental disease.
.PP
But nobody expected the rocket to suffer a sudden variation on its path, and falls right on the truck that Mariano Lopez uses to transport a blood sausages cargo.
.PP
Mariano, unconscious, lies on the floor besides his sausages and the truck's wreckage, spread all around. Some hours later, he wakes up really hungry, and eats an entire box of the radiated blood sausages.
.PP
But... what the hell is happening!? Mariano is becoming different: Every muscle grows, he becomes taller, his ugly face becomes a pretty superhero's, Captain 'S' (Capitan Sevilla), who discovers that everything was part of the evil Torrebruno's plan, with the true intention of ruling the World, starting by Seville.
.br

.SH TWO PARTS FX
The game has two parts. In order to play the second one, you have to finish the first, and get the password.
.PP
If you play to Captain 'S' (Capitan Sevilla) – The Remake from a writable device, you don't need enter the code again once you've obtained it by passing trough the first part.
.br

.SH THE MENU
Game's menu has the following structure:
.TP
.B 1. Start to play
.TP
.B 2. Current language: (Select this one to change the game language)
.TP
.B 3. Configure
.TP
3.1. Configure Game
.TP
3.1.1. Start on stage: Change between the two stages. If you haven't finished the first one, or you are playing from a not writable device, you will have to enter the password obtained by passing trough first stage.
.TP
3.1.2. Difficulty: Adjust difficulty to your taste between the three levels.
.TP
3.2. Configure screen
.TP
3.2.1. Detail level: There are 5 different detail levels, in order to keep game's smoothness with every graphic card, even the older ones.
.TP
3.2.2. Scanlines: Turn on or off as you prefer this TV emulation filter.
.TP
3.2.3. Resolution: Choose between 640x480 (original resolution), 800x600 or 1024x768.
.TP
3.2.4. Screen mode: Play as you prefer, fullscreen or windowed.
.TP
3.3. Configure Sound
.TP
3.3.1. FX Volume
.TP
3.3.2. Music Volume
.TP
3.4. Configure controls
.TP
3.4.1. Control system: Keyboard, Joystick (if there is any connected), or both.
.TP
3.4.2. Define keys
.TP
.B 4. Extras
.TP
4.1. See again the game's introduction
.TP
4.2. Game credits
.TP
.B 5. Exit to O.S.: Leaves the game, and return to Operative System
.TP
After some seconds without pressing any key, the game will start a demonstration mode.
.br

.SH FIRST PART: Mutants attacks Seville
On first part, you'll be in Seville, with its buildings, parks, building works, etc... Your objetive is to locate the Space Rocket which will allow you to travel to Congrio, the madhouse planetoid, second part scenary. But you'll have to be careful, for the nuclear blast has turned many of Seville's inhabitants into mutants, and now they are helping Torrebruno on his evil plans of conquer and destruction.
.PP
Try to evade contact with the following characters:
.TP
.B CURRO:
He's a pissed of worker, who whenever see you, will try to catch you. Evade him while you can, and try to kill him if you can't evade.
.TP
.B SEBASTIAN, MANOLITO & JOSELITO:
Three little friends each one more naughty than the other, who have fallen under Torrebruno's mental control. Their pranks will give you trouble, but don't hurt them... they are children after all.
.TP
.B MANOLO THE WAITER:
Sadistic and despicable character, affected by radiation, who however will attack you only when you will be under a sausage's effects. If you give him a good pair of forehand punchs, you will get the sausage that he has on his plate.
.TP
.B LONG PRETTY WILLOBY:
Hired gun. This time he's hired by Prof. Torrebruno. He grew up in a hostile environment, and it lead him to vice and corruption. Be careful of him.
.TP
.B FATTY BLACK JONES:
LONG PRETTY WILLOBY's partner, he's even more handy using the gun. Don't loose sight on him. These two evil men appears when you've spent a lot of time in the same screen.
.TP
.B DUMBO PINK:
No! You're not drunk. It's the last ELEPHANTUS VOLADORUS specimen. Looks innocent and funny, but... don't trust him.
.TP
.B GEOSINCOPATED ROBOTROID:
It keep its sight on you, and when you less expect it, he throw you a hydrolizated electrons beam.
.TP
.B VOLATILE HAMBURGUESOID:
Don't try to eat it! DESTROY IT!
.TP
.B DUSTBIN:
Stinker bin. Try to avoid him.
.TP
.B MARY GROUPY:
Insatiable fan of CAPTAIN 'S'. Don't let her come close: She has bad intentions.
.TP
.B AEROSTATIC RETORTER:
Autonomous aerospacial vigilance unit.
.TP
.B BRAVE BULL:
Bestial bull that persecutes you. Don't you ever let him get close.
.TP
.B GORGOJO CARRASQUERO:
Little alien who protects certain screen areas. He's little, but not harmless...
.TP
.B ALIENÍTICUS ALIENANTE:
Brutal beast, originary from the deepest of Congrio. Has been sent by Torrebruno for his evil plans.
.TP
.B CHEPPY TRON:
Armoured android, nearly impregnable.
.TP
.B ATTACK SOLDIER:
He's trained to kill. Be careful of his megaprotons photogun.
.TP
Apart from these enemies, you'll have a lot of surprises to evade: Mutants that are inside Seville's buildings and are throwing objects to kill you, mad automatic saws which try to mutilate you, lava rivers to evade, etc...
.TP
An adventurous path, until you reach the Interstratospheric Devices Launching Base, where a rocket is ready to launch for Congrio, where you can face Torrebruno and save Seville and the World.
.br

.SH SECOND PART: Dish of Congrio
Now, you are in Congrio, first magnitude planetoid used as madhouse. Pass through the temple ruins and potapropane refinery, come into the base, and ascend to the upper level. Then, use the computers, pass besides the combat hangars, and finally fight against Torrebruno to neutralize the Plasma Cannon. You're able to do it... Good luck!
.TP
 Your enemies in this second part are:
.TP
.B POSTMODERN BRONTOSAUR:
He raises without previous notice, and leaps on you. If you don't kill him, you won't pass the screen.
.TP
.B HIGHSCOOTER:
Security robot. Dangerous!!
.TP
.B WILLY THE FROGGY:
Congrio's faune defender. 
.TP
.B CYBORG SHOCK:
Couragous and strong refinery defender.
.TP
.B  VIBROCANNON:
Defends the base's upper level with his terrible plasma bullets.
.TP
.B TRACTO ARM:
Simple maintenance robot who becomes mad because of a photonic overcharge. He will try to catch you.
.TP
.B MYSTIC WARRIOR:
Defends the Congrio's ancient civilization ruins. 
.TP
.B ANIBOT TX-4:
Initially he was a complex computerizated nailcare robot, but Prof. Torrebruno has modified his code to make it a faithfull intruder detector and destroyer.
.TP
.B ALIENÍTICUS MINUSCULUS:
Congrio's surface inhabitant, armed with building mechanery. Don't trust him... even a bit.
.TP
.B ATTACK BATISCOP:
With a washing machine motor, it's much more dangerous that it seems. He has a amazing aim when shooting cannonballs.
.TP
.B PROFESSOR TORREBRUNO: Although he has a weak appearance, he has modified his own molecular structure, giving him a superhuman resistance. Besides, he can vanish and reappear wherever he wants. He is your Big Enemy, and won't allow you to turn off his plasma cannon. You will need to knock out him several times before you beat him. Beware of his proton gun... it's more dangerous than it seems.
.TP
These are your main enemies on Congrio planetoid, but... they're not all of them!!!
.br

.SH GAME SCREEN
The action developes on the upper side.
.TP
The part below, the marker, is composed by the following elements, from left to right:
.TP
.B Torrebruno's visor:
It shows to you what Torrebruno is doing at every moment. You will be able to see his bad temper, and his null politeness.
.TP
.B Morcillometer:
When you have transformed into Captain 'S' (Capitan Sevilla), a blood sausage will represent your energy. When it's finished, you will revert back to Mariano Lopez state.
.TP
.B Action:
This icon will represent the “Fire” key action. You can change it between different character options by pressing "Select" key.
.TP
.B Lives:
Here you can see how many lives you have left.
.TP
Besides, on the right bottom side, you will see how many sausages you've got left.
.br

.SH DEFAULT CONTROLS:
.B Movement:
Cursor keys
.TP
.B Fire:
Left control key
.TP
.B Selection:
Enter key
.TP
Use Selection control to eat the sausages when you are Mariano, and to choose between different superpowers of Captain 'S' (Capitan Sevilla).
.TP
Use Fire control to punch when you are Mariano, and to use the chosen superpower when you are Captain 'S' (Capitan Sevilla).
.br

.SH MARIANO'S ACTIONS
When you represent Mariano in the game, your possibilities are only a few. Try to evade every enemy character... if they touch you, you will lose a life. Otherwise, use your punchs to defend yourself, and look everywhere for any sausage to transform into Captain 'S' (Capitan Sevilla).
.TP
However, some of your enemies won't attack you when you are under this appearance.
.br

.SH CAPITAN SEVILLA (Captain 'S')'S ACTIONS
.B SUPERPUFF:
If the icon represents a fan, press the Fire key and almost everything on your path will be blown.
.TP
.B SUPERSHOOT:
If the icon represents a sausage... try to shoot!!! You will feel the power of Captain 'S' (Capitan Sevilla)!!
.TP
.B SUPERDEFENSE:
When radiation symbol is on screen... use it! You will be invulnerable for a few seconds.
.TP
Choose the superpower you need by pressing Select key. Besides those three superpowers, there are other three which don't need to be previously selected:
.TP
.B GLIDING:
Press Fire key quickly while you are on air (e.g.: while jumping).
.TP
.B SUPERJUMP:
You'll be able to jump giant leaps. Don't hesitate on using it. It's very useful.
.TP
.B SUPERSTRENGHT:
Whenever an enemy contacts you, you won't lose a life, just energy.
.br

.SH ADVICE FOR BEGINNERS
When you find a screen with two computers, use them until the Earth appears on their respective monitors. It will be useful.
.TP
When you find BRAVE BULL, the vicious bull, you will have to use SuperPuff to get him out of the screen. You will get a sausage.
.TP
Don't waste your sausages recklessly. Keep yourself as Mariano while you can, and you will reach much longer.
.TP
Be patient, and don't try to finish the game in just one day. It's hard, and requires much dedication.
.br

.SH DIFFERENCES WITH THE ORIGINAL GAME
As you know, this game is a remake of an original game by HiScore, released on 1.988 by the legendary software house Dinamic Software.
.TP
Apart from the graphic update, there are several things that we have changed, to give the game an actual look'n'feel, so it can satisfy actual gamers. Some of these changes are...
.TP
.B Mariano's jump:
Mariano's behavior during jumping is completely changed, allowing character's control while it's on air, and removing the bouncing that original game has whenever Mariano hits any obstacle.
.TP
.B Captain's superpowers:
We tried to give more importance to each superpower, in order to make them more useful than in the original game.
.TP
.B Game map:
The original map for the second part was very short (specially when compared with the first part). We made it a bit longer, to balance both parts, and get a longer game itself.
.TP
.B Geekism:
The game is full of references to classic games and cult movies. Try to find'em all!!!
.TP
And those are only the most important ones. The game has been completely adapted to current times, and tries to attract new players to great spanish classic games.
.br

.SH USER LICENSE
This game has been releasend under GPLv3 license. Please, visit the following website for further info: http://www.gnu.org/licenses/gpl-3.0.html
.br

.SH AUTHOR
The CAPITAN SEVILLA - THE REMAKE was written by Luis I. Garcia Ventura <benway@computeremuzone.com>
.PP
This manual page was written by Carlos Donizete Froes [a.k.a coringao] <coringao@riseup.net>, for the Debian project (but may be used by others).
