/* Allegro datafile object indexes, produced by grabber v4.2.1, MinGW32 */
/* Datafile: c:\Documents and Settings\Luis\Mis documentos\Desarrollo\Capitan\Capitan\data\sfx.dat */
/* Date: Wed Nov 19 19:05:34 2008 */
/* Do not hand edit! */

#define DF_SAGH                          0        /* SAMP */
#define DF_SALARM                        1        /* SAMP */
#define DF_SAPARECE                      2        /* SAMP */
#define DF_SAPATORRE                     3        /* SAMP */
#define DF_SAUTOLLEGA                    4        /* SAMP */
#define DF_SAUTOSALE                     5        /* SAMP */
#define DF_SBALON                        6        /* SAMP */
#define DF_SBESO                         7        /* SAMP */
#define DF_SBIRDS                        8        /* SAMP */
#define DF_SBOING                        9        /* SAMP */
#define DF_SCAIDA                        10       /* SAMP */
#define DF_SCANON                        11       /* SAMP */
#define DF_SCIG                          12       /* SAMP */
#define DF_SCOHETE                       13       /* SAMP */
#define DF_SCONV                         14       /* SAMP */
#define DF_SCOUNTD                       15       /* SAMP */
#define DF_SCRISTAL                      16       /* SAMP */
#define DF_SDECONV                       17       /* SAMP */
#define DF_SDESAPARECE                   18       /* SAMP */
#define DF_SDESAPATORRE                  19       /* SAMP */
#define DF_SDESTROYH                     20       /* SAMP */
#define DF_SDISPCEMENTO                  21       /* SAMP */
#define DF_SDISPLASER                    22       /* SAMP */
#define DF_SDISPLASER2                   23       /* SAMP */
#define DF_SDISPMORC                     24       /* SAMP */
#define DF_SEXPL                         25       /* SAMP */
#define DF_SGOLPE                        26       /* SAMP */
#define DF_SGOLPPUNO                     27       /* SAMP */
#define DF_SIMALO                        28       /* SAMP */
#define DF_SINTRUDER                     29       /* SAMP */
#define DF_SKEYBOARD                     30       /* SAMP */
#define DF_SLAVA01                       31       /* SAMP */
#define DF_SLAVA02                       32       /* SAMP */
#define DF_SMAMPORRO                     33       /* SAMP */
#define DF_SMMALO                        34       /* SAMP */
#define DF_SPEDO                         35       /* SAMP */
#define DF_SPIEDRAS                      36       /* SAMP */
#define DF_SPINZA                        37       /* SAMP */
#define DF_SPIS                          38       /* SAMP */
#define DF_SPOSTSALTO                    39       /* SAMP */
#define DF_SPUERTA                       40       /* SAMP */
#define DF_SRADIAC                       41       /* SAMP */
#define DF_SRALENTI                      42       /* SAMP */
#define DF_SRASCA                        43       /* SAMP */
#define DF_SROAR                         44       /* SAMP */
#define DF_SROBOCHAT                     45       /* SAMP */
#define DF_SROTO_000                     46       /* SAMP */
#define DF_SROTO_001                     47       /* SAMP */
#define DF_SSIERRA                       48       /* SAMP */
#define DF_SSILBA                        49       /* SAMP */
#define DF_SSOPLA                        50       /* SAMP */
#define DF_STIN                          51       /* SAMP */
#define DF_SVUELA                        52       /* SAMP */

